language: c

dist: xenial

env:
  global:
    PYTHONPATH=pip/src/
  matrix:
    - PYTHON=2.7.15
    - PYTHON=3.4.4
    - PYTHON=3.5.4
    - PYTHON=3.6.8
    - PYTHON=3.7.2
    - PYTHON=pypy2.7-6.0.0
    - PYTHON=pypy3.5-6.0.0

os:
  - linux
  - osx
  - windows

install:
  - git clone https://github.com/pypa/pip
  - git -C pip checkout 19.0.1
  - python buildpyz.py
  - python cipi.pyz
  - source cipi.sh
  - pip install tox-travis tox

script:
  - tox

after_success:
  - tox -e codecov
