language: c

dist: xenial

env:
  matrix:
    - PYTHON=2.7.15
    - PYTHON=3.4.4
    - PYTHON=3.5.4
    - PYTHON=3.6.8
    - PYTHON=3.7.2
    - PYTHON=pypy2.7-6.0.0
    - PYTHON=pypy3.5-6.0.0

os:
  - linux
  - osx
  - windows

install:
  - python -c 'import sys; print(sys.version); print(sys.executable); print(sys.prefix)'
  - git clone https://github.com/pypa/virtualenv
  - git -C virtualenv checkout 16.3.0
  - python virtualenv/virtualenv.py venv
  - venv/bin/python -m pip install --upgrade pip==19.0.1 setuptools==40.6.3
  - venv/bin/python -m pip install .
  - venv/bin/python -m cipi
  - source cipi.sh
  - pip install tox-travis tox

script:
  - tox

after_success:
  - tox -e codecov
