language: c

dist: xenial

jobs:
  include:
    - stage: "pyz"
      name: "Build PYZ"
      env:
        global:
          PYTHONPATH=$TRAVIS_BUILD_DIR/pip/src/
      os:
        - linux
      install:
        - python buildpyz.py

    - stage: "test"
      name: "Test"
      env:
        matrix:
          - PYTHON=2.7.15
          - PYTHON=3.4.4
          - PYTHON=3.5.4
          - PYTHON=3.6.8
          - PYTHON=3.7.2
          - PYTHON=pypy2.7-6.0.0
          - PYTHON=pypy3.5-6.0.0
      os:
        - linux
        - osx
        - windows
      install:
        - python cipi.pyz
        - source cipi.sh
        - python -m pip install tox-travis tox
      script:
        - tox
      after_success:
        - tox -e codecov

stages:
  - pyz
  - test
