dist: xenial

language: c

env:
  global:
    - CACHE_NAME=PYZ
  matrix:
    - PYTHON=2.7.15
    - PYTHON=3.4.4
    - PYTHON=3.5.4
    - PYTHON=3.6.8
    - PYTHON=3.7.2
    - PYTHON=pypy2.7-6.0.0
    - PYTHON=pypy3.5-6.0.0

os:
  - linux
  - osx
  - windows

install:
  - cp cache/cipi.pyz .
  - python cipi.pyz
  - source cipi.sh
  - python -m pip install tox-travis tox

script:
  - tox

after_success:
  - tox -e codecov

cache:
  directories:
  - cache

jobs:
  include:
    - stage: pyz
      name: Build PYZ
      language: python
      python: 3.7
      os: linux
      env:
        global:
          - PYTHONPATH=$TRAVIS_BUILD_DIR/pip/src/
          - CACHE_NAME=PYZ
      install:
        - echo hi
      script:
        - python buildpyz.py
        - cp cipi.pyz cache
      after_success:
        - echo hi

    - stage: test
      name: Test

stages:
  - pyz
  - test
