language: c

dist: xenial

env:
  matrix:
    - PYTHON=2.7.15
    - PYTHON=3.4.4
    - PYTHON=3.5.4
    - PYTHON=3.6.8
    - PYTHON=3.7.2
    - PYTHON=pypy2.7-6.0.0
    - PYTHON=pypy3.5-6.0.0

os:
  - linux
  - osx
  - windows

install:
  - python setup.py install --user .
  - python -m cipi
  - source cipi.sh
  - pip install tox-travis tox

script:
  - tox

after_success:
  - tox -e codecov
